DROP TABLE IF EXISTS category CASCADE;

CREATE TABLE category
(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(200) NOT NULL,
    sub_category VARCHAR(200),  
    category_level VARCHAR(200) NOT NULL, 
    active BOOLEAN DEFAULT TRUE
);