DROP TABLE IF EXISTS category;

CREATE TABLE category
(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(200) NOT NULL,
    sub_category VARCHAR(200),  
    category_level VARCHAR(200) NOT NULL, 
    active BOOLEAN DEFAULT TRUE, 
	created_by INT NOT NULL,
	created_date TIMESTAMP NOT NULL DEFAULT NOW(),
	last_modified_by INT NOT NULL,
	last_modified_date TIMESTAMP NOT NULL DEFAULT NOW()
);