DROP TABLE IF EXISTS event CASCADE;

CREATE TABLE event
(
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INT NOT NULL REFERENCES GEO_LOCATION,
    name VARCHAR(200) NOT NULL,
    category_id INT NOT NULL REFERENCES CATEGORY,  
    age_group VARCHAR(200),
    min_participants INT NOT NULL DEFAULT 1,
    max_participants  INT,
    details JSONB,
    active BOOLEAN DEFAULT TRUE
);