DROP TABLE IF EXISTS geo_location;

CREATE TABLE geo_location
(
    geo_location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    details JSONB,
    location GEOGRAPHY NOT NULL,
    active BOOLEAN DEFAULT TRUE, 
	created_by INT NOT NULL,
	created_date TIMESTAMP NOT NULL DEFAULT NOW(),
	last_modified_by INT NOT NULL,
	last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    version INT NOT NULL
);
